"""create_user_tables

Revision ID: 02a4b82efae3
Revises: None
Create Date: 2026-05-26 19:42:21.537752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a4b82efae3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор аккаунта'),
    sa.Column('email', sa.String(), nullable=False, comment='Основной email пользователя'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Статус активности аккаунта'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False, comment='Дата и время регистрации'),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_accounts_email'), 'accounts', ['email'], unique=True, schema='users')
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False, comment='ID профиля, совпадает с ID аккаунта'),
    sa.Column('username', sa.String(), nullable=False, comment='Уникальный логин пользователя'),
    sa.Column('display_name', sa.String(), nullable=True, comment='Отображаемое имя (публичное)'),
    sa.Column('avatar_url', sa.String(), nullable=True, comment='Ссылка на аватар'),
    sa.Column('bio', sa.String(length=200), nullable=True, comment='Описание профиля (до 200 символов)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False, comment='Дата и время последнего обновления профиля'),
    sa.ForeignKeyConstraint(['id'], ['users.accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_profiles_username'), 'profiles', ['username'], unique=True, schema='users')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID сессии'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID владельца сессии'),
    sa.Column('refresh_token_hash', sa.String(), nullable=False, comment='Хэш Refresh-токена'),
    sa.Column('device_info', sa.String(), nullable=True, comment='Информация об устройстве'),
    sa.Column('ip_address', sa.String(), nullable=True, comment='IP-адрес сессии'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False, comment='Время последней активности'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False, comment='Дата создания сессии'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Дата истечения сессии'),
    sa.ForeignKeyConstraint(['user_id'], ['users.accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True, schema='users')
    op.create_table('ui_settings',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя, владельца настроек'),
    sa.Column('theme', sa.String(), server_default='dark', nullable=False, comment='Выбранная тема оформления (dark/light)'),
    sa.Column('language', sa.String(), server_default='ru', nullable=False, comment='Язык интерфейса (ru/en)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ui_settings', schema='users')
    op.drop_index(op.f('ix_users_sessions_refresh_token_hash'), table_name='sessions', schema='users')
    op.drop_table('sessions', schema='users')
    op.drop_index(op.f('ix_users_profiles_username'), table_name='profiles', schema='users')
    op.drop_table('profiles', schema='users')
    op.drop_index(op.f('ix_users_accounts_email'), table_name='accounts', schema='users')
    op.drop_table('accounts', schema='users')
    # ### end Alembic commands ###
